---
title: "LiteratureReview_Git"
author: "Biraj Adhikari"
date: "5/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r installing required libraries}
#Package names
# Installing required packages if not installed yet

if("devtools" %in% rownames(installed.packages())   == FALSE){
  install.packages("devtools")}
library(devtools)

if("ggplot2" %in% rownames(installed.packages())   == FALSE){
  install.packages("ggplot2")}

if("dplyr" %in% rownames(installed.packages())   == FALSE){
  install.packages("dplyr")}

#for combining base and ggplot together
if("gridBase" %in% rownames(installed.packages())   == FALSE){
  install.packages("gridBase")}

#for network
if("igraph" %in% rownames(installed.packages())   == FALSE){
  install.packages("igraph")}

#for ggarrange
if("ggpubr" %in% rownames(installed.packages())   == FALSE){
  install.packages("ggpubr")}
#for sankey diagrams
if("networkD3" %in% rownames(installed.packages())   == FALSE){
  install.packages("networkD3")}

```

```{r loading libraries}
library(ggplot2)
library(networkD3)
library(dplyr)

```

FIGURE 7: Type of NCP studied
```{r}
ncp = read.csv('ncp_all_3May21.csv', header = TRUE, sep = ",")
ncp = ncp %>% filter(ecozone == "overall")

png(filename = "ncp_fig.png",            
  width = 1500,        
  height = 1000,
  res = 300,  
  
  ) 

ncp_fig = ncp %>% filter(ecozone =="overall") %>% ggplot(aes(x = reorder(NCP, -percent), y = percent, fill = category)) + geom_bar(stat= "identity") +
  scale_fill_manual(values = c("#ffb3b3", "#66cccc", "#b2df8a")) + 
  
              labs(x = "NCPs", y = "% of occurance", fill = "NCP Categories") + 
  scale_y_continuous(labels = scales::percent) +
              theme(legend.position = "bottom",
                    legend.title = element_text(size = 6),
                    legend.key.size = unit(0.5, 'cm'),
                    legend.text = element_text(size = 5),
                    axis.title.x = element_text(size = 7),
                    axis.title.y = element_text(size = 7),
                    axis.text = element_text(size = 5),
                    panel.background = element_rect(fill = "white"),
                    panel.grid.major = element_line(size = 0.15, linetype = "solid", colour = "#F0F0F0"),
                    panel.grid.minor = element_line(size = 0.15, linetype = "solid", colour = "#F0F0F0"))+
              coord_flip() 
 
ncp_fig
dev.off() 
```

ALTERNATIVE OPTION: Combination of Figure 7, Table 3 and Figure 9

```{r}
try = read.csv('try.csv', header = TRUE, sep = ",")

try = try %>% group_by(NCP) %>% 
  arrange(NCP, desc(Trend)) %>%
  mutate(lab_ypos = cumsum(count) - 0.5 * count)

png(filename = "ncp_fig_with_trends.png",            
  width = 1500,        
  height = 1000,
  res = 300,  
  ) 


ggplot(try, aes(x = reorder(NCP, count, FUN = sum), y = count)) + geom_col(aes(fill = Trend), width = 0.7) + 
 scale_fill_manual(values = c("#fc8d62", "#a6d854", "#a6a6a6")) + 
  geom_text(size = 1.7, aes(y = lab_ypos, label = for_label, group = Trend)) + 
              labs(x = "NCPs", y = "Occurrence", fill = "") + 
  
  #scale_y_continuous(labels = scales::percent) +
              theme(legend.position = "bottom",
                    legend.title = element_text(size = 6),
                    legend.key.size = unit(0.5, 'cm'),
                    legend.text = element_text(size = 5),
                    axis.title.x = element_text(size = 7),
                    axis.title.y = element_text(size = 7),
                    axis.text = element_text(size = 5),
                    panel.background = element_rect(fill = "white"),
                    panel.grid.major = element_line(size = 0.15, linetype = "solid", colour = "#F0F0F0"),
                    panel.grid.minor = element_line(size = 0.15, linetype = "solid", colour = "#F0F0F0"))+
  coord_flip() 
  
  
```



COMBINED FIGURE 10 and 11: DIRECT AND INDIRECT DRIVERS
```{r}
links = read.csv('drivers.csv', header = TRUE, sep = ",")

nodes <- data.frame(
  name=c(as.character(links$source), 
  as.character(links$target)) %>% unique()
)


links$IDsource <- match(links$source, nodes$name)-1 
links$IDtarget <- match(links$target, nodes$name)-1

#this is when filter is not applied:
nodes$group = as.factor(c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "j", "k", "j", "l", "l", rep("k", 5), "j", "k", "l", "l"))
#links$group = as.factor(c(rep("g1", 8), rep("g2", 7), rep("g3", 5), rep("g4", 3), rep("g5", 3), rep("g6",2), "g7", "g8"))
my_color =  'd3.scaleOrdinal() .domain(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "negative", "positive"]) .range(["#decbe4", "#d9d9d9","#fddaec", "#fb6a4a", "#fed9a6", "#b3cde3", "#e5d8bd", "#ccffe6", "#ffd9cc", "#ffb3b3", "#b2df8a", "#66cccc", "#fbb4ae", "#ccebc5"])'


# Make the Network
drivers = sankeyNetwork(Links = links, Nodes = nodes,
              Source = "IDsource", Target = "IDtarget",
              Value = "value", NodeID = "name", colourScale = my_color, NodeGroup = "group", LinkGroup = "type",
              sinksRight = TRUE, nodeWidth = 15, nodePadding = 6, fontSize = 18)

drivers

```


